name: Clans
version: ${project.version}
main: repo.ruinspvp.clans.Clans
commands:
    test:
    points:
    credits:
    rank:
    setrank:
    givepoints:
    givecredits:
    clan:
    scoreboard:
    punish:
